// This file is automatically generated. Do not edit manually.

export const cliCommands = [
    {
        "text": "ops",
        "items": [
            {
                "text": "add",
                "items": [
                    {
                        "text": "db",
                        "link": "/cli-commands/ops/add/db"
                    },
                    {
                        "text": "ingress",
                        "link": "/cli-commands/ops/add/ingress"
                    },
                    {
                        "text": "microservice",
                        "link": "/cli-commands/ops/add/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "create",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/create/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "deploy",
                "items": [
                    {
                        "text": "all",
                        "link": "/cli-commands/ops/deploy/all"
                    },
                    {
                        "text": "ingress",
                        "link": "/cli-commands/ops/deploy/ingress"
                    },
                    {
                        "text": "microservice",
                        "link": "/cli-commands/ops/deploy/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "destroy",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/destroy/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "expose",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/expose/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "init",
                "link": "/cli-commands/ops/init"
            },
            {
                "text": "remove",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/remove/cluster"
                    },
                    {
                        "text": "microservice",
                        "link": "/cli-commands/ops/remove/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "setup",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/setup/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "start",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/start/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "status",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/status/cluster"
                    },
                    {
                        "text": "helm",
                        "link": "/cli-commands/ops/status/helm"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "stop",
                "items": [
                    {
                        "text": "cluster",
                        "link": "/cli-commands/ops/stop/cluster"
                    }
                ],
                "collapsed": true
            }
        ],
        "collapsed": false
    },
    {
        "text": "proj",
        "items": [
            {
                "text": "add",
                "items": [
                    {
                        "text": "context",
                        "link": "/cli-commands/proj/add/context"
                    },
                    {
                        "text": "microservice",
                        "link": "/cli-commands/proj/add/microservice"
                    },
                    {
                        "text": "module",
                        "link": "/cli-commands/proj/add/module"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "init",
                "link": "/cli-commands/proj/init"
            }
        ],
        "collapsed": false
    }
];
