// This file is automatically generated. Do not edit manually.

export const resources = [
    {
        "text": "ops",
        "items": [
            {
                "text": "alertmanager",
                "items": [
                    {
                        "text": "install",
                        "link": "/docs/cli-commands/ops/install/alertmanager"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "all",
                "items": [
                    {
                        "text": "deploy",
                        "link": "/docs/cli-commands/ops/deploy/all"
                    },
                    {
                        "text": "install",
                        "link": "/docs/cli-commands/ops/install/all"
                    },
                    {
                        "text": "undeploy",
                        "link": "/docs/cli-commands/ops/undeploy/all"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "cluster",
                "items": [
                    {
                        "text": "create",
                        "link": "/docs/cli-commands/ops/create/cluster"
                    },
                    {
                        "text": "destroy",
                        "link": "/docs/cli-commands/ops/destroy/cluster"
                    },
                    {
                        "text": "expose",
                        "link": "/docs/cli-commands/ops/expose/cluster"
                    },
                    {
                        "text": "remove",
                        "link": "/docs/cli-commands/ops/remove/cluster"
                    },
                    {
                        "text": "setup",
                        "link": "/docs/cli-commands/ops/setup/cluster"
                    },
                    {
                        "text": "start",
                        "link": "/docs/cli-commands/ops/start/cluster"
                    },
                    {
                        "text": "status",
                        "link": "/docs/cli-commands/ops/status/cluster"
                    },
                    {
                        "text": "stop",
                        "link": "/docs/cli-commands/ops/stop/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "db",
                "items": [
                    {
                        "text": "add",
                        "link": "/docs/cli-commands/ops/add/db"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "grafana",
                "items": [
                    {
                        "text": "install",
                        "link": "/docs/cli-commands/ops/install/grafana"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "helm",
                "items": [
                    {
                        "text": "status",
                        "link": "/docs/cli-commands/ops/status/helm"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "ingress",
                "items": [
                    {
                        "text": "add",
                        "link": "/docs/cli-commands/ops/add/ingress"
                    },
                    {
                        "text": "install",
                        "link": "/docs/cli-commands/ops/install/ingress"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "kubectl",
                "items": [
                    {
                        "text": "exec",
                        "link": "/docs/cli-commands/ops/exec/kubectl"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "microservice",
                "items": [
                    {
                        "text": "add",
                        "link": "/docs/cli-commands/ops/add/microservice"
                    },
                    {
                        "text": "deploy",
                        "link": "/docs/cli-commands/ops/deploy/microservice"
                    },
                    {
                        "text": "remove",
                        "link": "/docs/cli-commands/ops/remove/microservice"
                    },
                    {
                        "text": "rolling",
                        "link": "/docs/cli-commands/ops/rolling/microservice"
                    },
                    {
                        "text": "scale",
                        "link": "/docs/cli-commands/ops/scale/microservice"
                    },
                    {
                        "text": "undeploy",
                        "link": "/docs/cli-commands/ops/undeploy/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "minikube",
                "items": [
                    {
                        "text": "exec",
                        "link": "/docs/cli-commands/ops/exec/minikube"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "prometheus",
                "items": [
                    {
                        "text": "install",
                        "link": "/docs/cli-commands/ops/install/prometheus"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "terraform",
                "items": [
                    {
                        "text": "exec",
                        "link": "/docs/cli-commands/ops/exec/terraform"
                    }
                ],
                "collapsed": true
            }
        ],
        "collapsed": false
    },
    {
        "text": "proj",
        "items": [
            {
                "text": "context",
                "items": [
                    {
                        "text": "add",
                        "link": "/docs/cli-commands/proj/add/context"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "microservice",
                "items": [
                    {
                        "text": "add",
                        "link": "/docs/cli-commands/proj/add/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "module",
                "items": [
                    {
                        "text": "add",
                        "link": "/docs/cli-commands/proj/add/module"
                    }
                ],
                "collapsed": true
            }
        ],
        "collapsed": false
    }
];
