// This file is automatically generated. Do not edit manually.

export const sidebar = [
  {
    text: 'Documentation',
    items: [
      {
        text: 'Getting Started',
        collapsed: false,
        items: [
          { text: 'Introduction', link: '/getting-started/introduction' },
          { text: 'Requirements', link: '/getting-started/requirements' },
          { text: 'How to Install', link: '/getting-started/how-to-install' },
        ],
      },
      {
        text: 'CLI Commands',
        collapsed: false,
        items: [
    {
        "text": "Proj",
        "items": [
            {
                "text": "Add",
                "items": [
                    {
                        "text": "Context",
                        "link": "/cli-commands/proj/add/context"
                    },
                    {
                        "text": "Microservice",
                        "link": "/cli-commands/proj/add/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Init",
                "link": "/cli-commands/proj/init"
            }
        ]
    }
]
      }
    ]
  }
];
