// This file is automatically generated. Do not edit manually.

export const sidebar = [
  {
    text: 'Documentation',
    items: [
      {
        text: 'Getting Started',
        collapsed: false,
        items: [
          { text: 'Introduction', link: '/getting-started/introduction' },
          { text: 'Requirements', link: '/getting-started/requirements' },
          { text: 'How to Install', link: '/getting-started/how-to-install' },
        ],
      },
      {
        text: 'CLI Commands',
        collapsed: false,
        items: [
    {
        "text": "Ops",
        "items": [
            {
                "text": "Add",
                "items": [
                    {
                        "text": "Db",
                        "link": "/cli-commands/ops/add/db"
                    },
                    {
                        "text": "Ingress",
                        "link": "/cli-commands/ops/add/ingress"
                    },
                    {
                        "text": "Microservice",
                        "link": "/cli-commands/ops/add/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Create",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/create/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Deploy",
                "items": [
                    {
                        "text": "All",
                        "link": "/cli-commands/ops/deploy/all"
                    },
                    {
                        "text": "Ingress",
                        "link": "/cli-commands/ops/deploy/ingress"
                    },
                    {
                        "text": "Microservice",
                        "link": "/cli-commands/ops/deploy/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Destroy",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/destroy/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Expose",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/expose/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Init",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/init/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Init",
                "link": "/cli-commands/ops/init"
            },
            {
                "text": "Remove",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/remove/cluster"
                    },
                    {
                        "text": "Microservice",
                        "link": "/cli-commands/ops/remove/microservice"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Start",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/start/cluster"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Status",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/status/cluster"
                    },
                    {
                        "text": "Helm",
                        "link": "/cli-commands/ops/status/helm"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Stop",
                "items": [
                    {
                        "text": "Cluster",
                        "link": "/cli-commands/ops/stop/cluster"
                    }
                ],
                "collapsed": true
            }
        ],
        "collapsed": false
    },
    {
        "text": "Proj",
        "items": [
            {
                "text": "Add",
                "items": [
                    {
                        "text": "Context",
                        "link": "/cli-commands/proj/add/context"
                    },
                    {
                        "text": "Microservice",
                        "link": "/cli-commands/proj/add/microservice"
                    },
                    {
                        "text": "Module",
                        "link": "/cli-commands/proj/add/module"
                    }
                ],
                "collapsed": true
            },
            {
                "text": "Init",
                "link": "/cli-commands/proj/init"
            }
        ],
        "collapsed": false
    }
]
      }
    ]
  }
];
